# Generated by Django 2.2 on 2021-07-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc', models.CharField(max_length=50)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=20)),
                ('movimiento', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=15)),
                ('lugar', models.CharField(default='Desconocido', max_length=50)),
                ('usuario', models.CharField(default='Desconocido', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='neumatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc', models.CharField(max_length=50)),
                ('idP', models.CharField(max_length=20)),
                ('pos', models.CharField(max_length=10)),
                ('trailer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='stripeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('id_stripe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=15)),
                ('layout', models.CharField(max_length=10)),
            ],
        ),
    ]
