# Generated by Django 2.2 on 2021-07-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solisticaAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='layout',
            field=models.CharField(max_length=25),
        ),
    ]
