# Generated by Django 2.2 on 2021-08-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solisticaAPI', '0002_auto_20210726_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='presion',
            field=models.FloatField(default=0.0),
        ),
    ]
