# Generated by Django 2.2 on 2022-03-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solisticaAPI', '0003_historial_presion'),
    ]

    operations = [
        migrations.AddField(
            model_name='neumatico',
            name='test',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
