# Generated by Django 2.2 on 2022-03-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solisticaAPI', '0004_neumatico_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neumatico',
            name='test',
        ),
    ]
