# Generated by Django 2.2 on 2022-04-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solisticaAPI', '0008_auto_20220418_1640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='validacion',
        ),
    ]
