# Generated by Django 2.2 on 2022-04-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solisticaAPI', '0009_delete_validacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='validaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=20)),
                ('idlec', models.CharField(max_length=10)),
                ('coordenadas', models.CharField(max_length=50)),
            ],
        ),
    ]
