# Generated by Django 2.2 on 2022-04-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solisticaAPI', '0010_validaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validaciones',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
