# Generated by Django 2.2 on 2022-04-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solisticaAPI', '0011_auto_20220418_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validaciones',
            old_name='idlec',
            new_name='idlector',
        ),
    ]
