# Generated by Django 2.2 on 2022-05-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solisticaAPI', '0012_auto_20220418_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validaciones',
            name='idlector',
        ),
        migrations.AddField(
            model_name='historial',
            name='idantena',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AddField(
            model_name='validaciones',
            name='idantena',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AddField(
            model_name='validaciones',
            name='lector',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='validaciones',
            name='coordenadas',
            field=models.CharField(default='19.82976,-98.97317', max_length=50),
        ),
    ]
