# Generated by Django 2.2 on 2022-05-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solisticaAPI', '0013_auto_20220511_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='idantena',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='validaciones',
            name='coordenadas',
            field=models.CharField(default='19.82976,-98.97317', max_length=100),
        ),
        migrations.AlterField(
            model_name='validaciones',
            name='idantena',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
    ]
