# Generated by Django 2.2 on 2022-05-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solisticaAPI', '0016_auto_20220511_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validaciones',
            name='lector',
            field=models.SlugField(default='1', max_length=20),
        ),
    ]
