# Generated by Django 2.2 on 2022-05-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solisticaAPI', '0018_auto_20220511_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='antena',
            field=models.SlugField(default='Desconocido'),
        ),
        migrations.AlterField(
            model_name='validaciones',
            name='antena',
            field=models.SlugField(default='Desconocido'),
        ),
        migrations.AlterField(
            model_name='validaciones',
            name='coordenadas',
            field=models.SlugField(default='Desconocido'),
        ),
        migrations.AlterField(
            model_name='validaciones',
            name='lector',
            field=models.SlugField(default='Desconocido', max_length=20),
        ),
    ]
