# Generated by Django 2.2 on 2022-05-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solisticaAPI', '0019_auto_20220511_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validaciones',
            old_name='lector',
            new_name='equipo',
        ),
    ]
